### ISSUE TITLE
Target [Butschster\Head\Contracts\MetaTags\MetaInterface] is not instantiable.

### ISSUE THREAD

**Issue by Luismij** [butschster/LaravelMetaTags#12]
I'm getting this error in LAravel 6
Target [Butschster\Head\Contracts\MetaTags\MetaInterface] is not instantiable.

Please help

**Comment by butschster** [comment]
Hi. I need more information about the problem. When did you get this error?

**Comment by Luismij** [comment]
There is no Register method in` App\Providers\MetaTagsServiceProvider.`
This is the code in that class:
`<?php

namespace App\Providers;

use Butschster\Head\Contracts\Packages\PackageInterface;
use Butschster\Head\Facades\PackageManager;
use Butschster\Head\MetaTags\Meta;
use Butschster\Head\Contracts\MetaTags\MetaInterface;
use Butschster\Head\Contracts\Packages\ManagerInterface;
use Butschster\Head\Providers\MetaTagsApplicationServiceProvider as ServiceProvider;

class MetaTagsServiceProvider extends ServiceProvider
{
    protected function packages()
    {
        // Create your own packages here
    }

    // if you don't want to change anything in this method just remove it
    protected function registerMeta(): void
    {
        $this->app->singleton(MetaInterface::class, function () {
            $meta = new Meta(
                $this->app[ManagerInterface::class],
                $this->app['config']
            );

            // It just an imagination, you can automatically
            // add favicon if it exists
            // if (file_exists(public_path('favicon.ico'))) {
            //    $meta->setFavicon('/favicon.ico');
            // }

            // This method gets default values from config and creates tags, includes default packages, e.t.c
            // If you don't want to use default values just remove it.
            $meta->initialize();

            return $meta;
        });
    }
}`

**Comment by Luismij** [comment]
There is no Register method in App\Providers\MetaTagsServiceProvider.
This is the code in that class:
```
protected function packages()
    {
        // Create your own packages here
    }

    // if you don't want to change anything in this method just remove it
    protected function registerMeta(): void
    {
        $this->app->singleton(MetaInterface::class, function () {
            $meta = new Meta(
                $this->app[ManagerInterface::class],
                $this->app['config']
            );

            // It just an imagination, you can automatically
            // add favicon if it exists
            // if (file_exists(public_path('favicon.ico'))) {
            //    $meta->setFavicon('/favicon.ico');
            // }

            // This method gets default values from config and creates tags, includes default packages, e.t.c
            // If you don't want to use default values just remove it.
            $meta->initialize();

            return $meta;
        });
    }
```

**Comment by butschster** [comment]
And what about version? When did you get this error?

**Comment by Luismij** [comment]
I'll try to explain what's happening.

I followed the install instructions

1. Command: Composer require...
2. Command: meta-tags:install ...
3. The MetaTagsServiceProvider  exists

And i created this class:

```php
use Butschster\Head\MetaTags\MetaInterface;
use App\Repositories\BlogsRepository;

class BlogsController extends AppBaseController
{
    /** @var  BlogsRepository */
    private $blogsRepository;
    protected $meta;

    public function __construct(BlogsRepository $blogsRepo, MetaInterface $meta)
    {
        $this->meta = $meta;
        $this->blogsRepository = $blogsRepo;
    }
public function blogPosts()
    {
        $blogPosts = Blogs::where('status', '=', 'Active')->paginate(4);
       
        $data['blogPosts'] = $blogPosts;
        $this->meta

            // Will render "Home page - Default Title"
            ->prependTitle('Home page')

            // Will include next, prev, canonical links
            ->setPaginationLinks($data)

            // Will change default favicon
            ->setFavicon('/favicon-index.ico');
        return view('front.blog.blogPosts')->with($data);
    }
```

Now I'm getting this error:

> Class Butschster\Head\MetaTags\MetaInterface does not exist

What I'm doing wrong?
I really wants to use this library, but please help me.
Let me know if you need more information.
Thanks in advance

**Comment by Luismij** [comment]
Will be awesome if you have a full example/tutorial.

**Comment by butschster** [comment]
**There can be two reasons.** 
1. Problems in `App\Providers\MetaTagsServiceProvider`, but you don't have any.
2. This service provider was not add to the providers array in your app `config/app.php`

**Comment by majorsabbir** [comment]
@Luismij If your are in same situation, remove `app/Providers/MetaTagsServiceProvider.php`, `App\Providers\MetaTagsServiceProvider::class,` line from `config/app.php` and config/meta_tags.php and run  `composer remove butschster/meta-tags`. Install again. After installation run `php artisan optimize:clear`. This procedure works for me.

**Comment by jrson83** [comment]
@majorsabbir Thank you!!! I had the same issue after installing on Laravel 7. I followed your instructions and it fixed the error.

**Comment by Luismij** [comment]
Thank you I'll try it and let you know if works for me

**Comment by livevsonline** [comment]
@majorsabbir I still have this problem also tried uninstalling and all

**Comment by majorsabbir** [comment]
@livevsonline make sure you uninstall LaravelMetaTags first. run `php artisan config:clear`, then follow the installation process again [Laravel Meta Tags Installation](https://github.com/butschster/LaravelMetaTags#user-content-installation-and-configuration).  if it still doesn't work run `php artisan optimize`.
**Note:**  After running `php artisan meta-tags:install` command if you found there is no meta-tags.php in config folder, check your current user permission.
