### ISSUE TITLE
Cannot install on Laravel 7

### ISSUE THREAD

**Issue by rjsworking** [butschster/LaravelMetaTags#15]
@butschster

Almost done :)

You forgot to remove the use statements: use Illuminate\Console\DetectsApplicationNamespace; and
use DetectsApplicationNamespace

**Comment by butschster** [comment]
OMG :) I did it, but didn't include to commit.

**Comment by butschster** [comment]
Thank you for help!

**Comment by rjsworking** [comment]
You're welcome. Glad to help

Cheers

**Comment by olimortimer** [comment]
I think the readme needs updating - "Laravel 5.6 to 6.x"
