### ISSUE TITLE
Default title separator not taken from config file

### ISSUE THREAD

**Issue by vmlinuz82** [butschster/LaravelMetaTags#16]

**Comment by butschster** [comment]
Привет

Сейчас значение из конфига берется в момент инициализации пакета и добавляется с помощью метода `setTitle`. Я так понимаю, далее, ты опять используешь этот же метод и переопределяешь заголовок по умолчанию. По идее в коде ты должен использовать уже метод `prependTitle`.

**Comment by vmlinuz82** [comment]
Yes I use `use Butschster\Head\Facades\Meta;` method and in my method set title like this `Meta::prependTitle(trans('something'));` Title is generated, App name part is ok but separator is | not - that i set in config file.

**Comment by butschster** [comment]
А, блин, я не в ту сторону смотрел, почему то подумал про title, а оказался separator. Сейчас посмотрю еще раз. Спасибо за репорт
