### ISSUE TITLE
OpenGraph wrong tag attributename

### ISSUE THREAD

**Issue by p0g** [butschster/LaravelMetaTags#17]
In the OpenGraphPackage you are using the same tag generator like other meta-tags, but this is not working for OpenGraph:
Generated, wrong tag: `<meta name="og:type" content="website">`
Correct tag would be: `<meta property="og:type" content="website">`

See: https://developers.facebook.com/docs/sharing/webmasters

My quick "bugfix" local, is to extend _vendor/butschster/meta-tags/src/Packages/Entities/Concerns/ManageMeta.php_ with:

_public function addOgMeta(string $key, string $content)
    {
        $key = $this->prefix.$key;
        $this->tags->put($key, Tag::meta([
            'property' => $key,
            'content' => $content,
        ]));
        return $this;
    }_

And replace `$this->addMeta` with `$this->addOgMeta` in _vendor/butschster/meta-tags/src/Packages/Entities/OpenGraphPackage.php_

**Comment by butschster** [comment]
Tank you!
