### ISSUE TITLE
access tag value

### ISSUE THREAD

**Issue by tokomeno** [butschster/LaravelMetaTags#18]
I need to access meta tag value but when I get a tag and then trying to get value property is private, is there any way to do that?

My current code is:
`Meta::getTag("title")->title`

**Comment by butschster** [comment]
Hi! Try this 

```
dd(Meta::getTitle()->getAttributes());
```

**Comment by olimortimer** [comment]
Has this changed, as when I use your example @butschster it gives me the following error;

> Call to undefined method Butschster\Head\MetaTags\Entities\Title::getAttributes()
