### ISSUE TITLE
with PHP 8 I got error "require int, null given"

### ISSUE THREAD

**Issue by DenisDangerous** [butschster/LaravelMetaTags#26]
src/MetaTags/Entities/Title.php
with PHP 8 I got error "require int, null given"

fix it with adding "|null"
line 39:  public function __construct(string $title = null, int|null $maxLength = self::DEFAULT_LENGTH)

**Comment by butschster** [comment]
Hi! 
I couldn't use `__construct(string $title = null, int|null $maxLength = self::DEFAULT_LENGTH)` this style, because this code is incompatible with 7.x version.
I've made some fixes and you can try new version.
