### ISSUE TITLE
[Butschster\Head\Contracts\MetaTags\MetaInterface] is not instantiable. on Laravel 6

### ISSUE THREAD

**Issue by majorsabbir** [butschster/LaravelMetaTags#3]
I tried both way
Illuminate \ Contracts \ Container \ BindingResolutionException
Target [Butschster\Head\Contracts\MetaTags\MetaInterface] is not instantiable.

ReflectionException
Class Butschster\Head\MetaTags\MetaInterface does not exist

**Comment by majorsabbir** [comment]
Issue has been resolved

**Comment by mavsan** [comment]
Ларавел 6. Использую знаменитый https://github.com/barryvdh/laravel-ide-helper. После установки пакета вот что выдает генератор:

`php artisan ide-helper:generate
Exception: Target [Butschster\Head\Contracts\MetaTags\MetaInterface] is not instantiable.
Skipping \Butschster\Head\Facades\Meta.
Exception: Target [Butschster\Head\Contracts\Packages\ManagerInterface] is not instantiable.
Skipping \Butschster\Head\Facades\PackageManager.
Exception: Target [Butschster\Head\Contracts\MetaTags\MetaInterface] is not instantiable.
Skipping \Butschster\Head\Facades\Meta.
Exception: Target [Butschster\Head\Contracts\Packages\ManagerInterface] is not instantiable.
Skipping \Butschster\Head\Facades\PackageManager.`

При этом в фронтэнде и в контроллере все нормально отрабатывает.

**Comment by butschster** [comment]
Скорее всего это связано с этим https://github.com/butschster/LaravelMetaTags/blob/master/src/Providers/MetaTagsApplicationServiceProvider.php#L27

Для консоли эти сервисы не регистрируются. Думаю, что можно убрать это условие.

**Comment by Luismij** [comment]
I'm getting the same error in Laravel 6.

**Comment by rammi22** [comment]
Same error in Laravel 7
