### ISSUE TITLE
pass variable in $og->addImage( )

### ISSUE THREAD

**Issue by manishlok** [butschster/LaravelMetaTags#33]
Hi, this package is vary helpful to me.
How to pass variable in $og->addImage( );
Eg. :
$image='https://site.com';
$og->addImage($image);  // Not working
but
->setTitle($site->title);  // is working

**Comment by butschster** [comment]
Hi!

After OgPackage initialization you should register it.

```php
$og = new Butschster\Head\Packages\Entities\OpenGraphPackage('some_name');

$og->setType('website')
   ->setSiteName('My awesome site')
   ->setTitle('Post title');
   
// You can render itself

$og->toHtml();
// <meta name="og:type" content="website">
// <meta name="og:site_name" content="My awesome site">
// <meta name="og:title" content="Post title">

// Or just register this package in Meta class and it will be rendered automatically
Meta::registerPackage($og);
```

**Comment by manishlok** [comment]
Thanks for reply.
I want to pass a variable in addImage( );
When I pass variable in set attribute , It works
$og->setType($site->type)     // working
   ->setSiteName($site->name)   // working
   ->setTitle($site->title);   // working
But when I pass variable in add attribute , It doesn't work
Eg.:
$og->addImage($site->image)   // not working

**Comment by butschster** [comment]
> Thanks for reply.
> I want to pass a variable in addImage( );
> When I pass variable in set attribute , It works
> $og->setType($site->type) // working
> ->setSiteName($site->name) // working
> ->setTitle($site->title); // working
> But when I pass variable in add attribute , It doesn't work
> Eg.:
> $og->addImage($site->image) // not working

Please show me full code, it will be easier to understand your problem. 

Try to render `$og` object locally. 
```php
$og->setType($site->type) // working
->setSiteName($site->name) // working
->setTitle($site->title)
->addImage($site->image) // not working

dd($og->toHtml());
```

This package has unit tests coverage and you can see examples right in this tests https://github.com/butschster/LaravelMetaTags/blob/master/tests/Packages/Entities/OpenGraphPackageTest.php#L50
