### ISSUE TITLE
phpunit tests fail when @meta_tags is in a view

### ISSUE THREAD

**Issue by SvanThuijl** [butschster/LaravelMetaTags#4]
I'm using this package for a while which works great. Now I am writing tests for my application but they fail when @meta_tags is present in the view.

Any idea how to resolve this?

I already tried to to remove all meta data in my custom code. This does not resolve the issue.

The exception
```
(1/1) InvalidArgumentException
Action Facade\Ignition\Http\Controllers\ShareReportController not defined.
```

The test
```
    public function testBasicTest()
    {
//        $this->withExceptionHandling();
        $response = $this->get('/');
        $response->dump();

        $response->assertStatus(200);
    }
```

Php unit result
```
F                                                                  2 / 2 (100%)

Time: 278 ms, Memory: 28.00 MB

There was 1 failure:

1) Tests\Feature\ExampleTest::testBasicTest
Expected status code 200 but received 500.
Failed asserting that false is true.

/Users/simonvanthuijl/PhpstormProjects/gv/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:166
/Users/simonvanthuijl/PhpstormProjects/gv/tests/Feature/ExampleTest.php:21

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
Simons-MacBook-Pro:gv simonvanthuijl$ 

```

html output from the dump function
<img width="1081" alt="Screen Shot 2019-10-22 at 00 20 29 " src="https://user-images.githubusercontent.com/2386327/67259047-c83da900-f461-11e9-998a-b2e7dcecb2a7.png">

**Comment by butschster** [comment]
Hello! Sorry for long answer.

Try to check

**Comment by SvanThuijl** [comment]
The issue has been resolved. I updates all dependencies so I am not sure if it was your package. I've seen issues with other packages with he same error so could have been a Laravel issue.
