### ISSUE TITLE
Cannot call abstract method

### ISSUE THREAD

**Issue by piep14** [butschster/LaravelMetaTags#40]
Hello,

If I write this code, as the doc says, I get this message returned by phpStorm. My page doesn't bug but the editor doesn't seem to like it.

```
use Butschster\Head\Facades\Meta;

Meta::setTitle('Dashboard')
            ->setDescription('Dashboard');
```

_Cannot call abstract method 'MetaInterface::setTitle'_

Is there anything I can do? 
Thank you

**Comment by 33Piter** [comment]
This is a bug from PhpStorm 2021.2.4 (and perhaps other earlier versions). I updated to 2021.3 (https://www.jetbrains.com/phpstorm/whatsnew/) and the issue is fixed.
