### ISSUE TITLE
Support for property tag

### ISSUE THREAD

**Issue by adantart** [butschster/LaravelMetaTags#48]
Is there any way to include "property" tag, besides or instead of "name"?

For example, many OG meta are documented to be written with property tag:
https://ogp.me/#structured

How can I write something like this ?

```
<meta property="og:title" content="The Rock" />
<meta property="og:type" content="video.movie" />
<meta property="og:url" content="https://www.imdb.com/title/tt0117500/" />
<meta property="og:image" content="https://ia.media-imdb.com/images/rock.jpg" />

```
Thank you

**Comment by butschster** [comment]
https://github.com/butschster/LaravelMetaTags#opengraphpackage

**Comment by bbashy** [comment]
Maybe they thought that it uses name="" and not property="" because the readme says so;
```
// <meta name="og:type" content="website">
```

It does in fact generate;
```
<meta property="og:type" content="website">
```
