### ISSUE TITLE
Some Name

### ISSUE THREAD

**Issue by rlidev** [butschster/LaravelMetaTags#49]
What is the name that I have to put here? I don't understand this part, thanks

$og = new Butschster\Head\Packages\Entities\OpenGraphPackage('some_name');

**Comment by butschster** [comment]
> What is the name that I have to put here? I don't understand this part, thanks
> 
> $og = new Butschster\Head\Packages\Entities\OpenGraphPackage('some_name');

Hi! It's just a unique key, feel free to use any key.
