### ISSUE TITLE
query string в canonical link и paginator links

### ISSUE THREAD

**Issue by intruder897** [butschster/LaravelMetaTags#5]
canonical/paginator links выводят не корректный результат 

https://site.test/news?category=855%2C257%2C216&amp;amp;order=new&amp;amp;dir=desc&amp;amp;archive=true

**Comment by butschster** [comment]
А можешь пример использования прислать?

**Comment by intruder897** [comment]
не совсем понял что требуется, но использую так:

```
$params = $request->except('page');
Meta::setCanonical(route('news.filter', $params));
```

**Comment by butschster** [comment]
Нашел причину, при сборке элемента очищались с помощью `htmlspecialchars` все значения атрибутов. Убрал ее. 
Сможешь проверить на master ветке? А я после этого релиз выпущу

**Comment by intruder897** [comment]
все работает
