### ISSUE TITLE
Target [Butschster\Head\Contracts\MetaTags\MetaInterface] is not instantiable.

### ISSUE THREAD

**Issue by faridsa** [butschster/LaravelMetaTags#52]
Using butschster/meta-tags v2.3.0 under Laravel 9.51

**My controller**
1. use \Butschster\Head\Facades\Meta;
2. in index function: `Meta::setTitle('Ofertas');`
3. In blade template `{!! Meta::toHtml() !!}`

**Comment by wizard-85** [comment]
@faridsa Add  \App\Providers\MetaTagsServiceProvider::class, to config/app.php to providers array
