### ISSUE TITLE
How to generate custom meta tag?

### ISSUE THREAD

**Issue by rjsworking** [butschster/LaravelMetaTags#6]
Hi
I need to create custom meta tags like this one `<meta itemprop="arc:custom-name" content="meta content">` but even I pass an empty sting to name, the result is `<meta name="" itemprop="arc:custom-name" content="meta content">`.

Is there any way to achieve the pretended output?

Thanks in advance.

Cheers
rjs

**Comment by butschster** [comment]
Hi!

```php
use Butschster\Head\Facades\Meta;
use Butschster\Head\MetaTags\Entities\Tag;

...

Meta::addTag('my-custom-super-tag', new Tag('meta', [
    'itemprop' => 'arc:custom-name',
    'content' => 'meta content'
]));
```
will generate

```html
<meta itemprop="arc:custom-name" content="meta content">
```

**Comment by rjsworking** [comment]
Hi.

Thank you very much :) . Working as expected.

Cheers
rjs
