### ISSUE TITLE
AddProviderToBootstrapFile Error

### ISSUE THREAD

**Issue by codetec-info** [butschster/LaravelMetaTags#64]
I am using Laravel 10. When I update the package from 3.0.0 to 3.0.2, I got an error:

Whoops\Run::handleError("A void function must not return a value", "butschster\meta-tags\src\Console\InstallCommand.php")

if (file_exists($this->getLaravel()->bootstrapPath('providers.php'))) {
       // @phpstan-ignore-next-line
       return ServiceProvider::addProviderToBootstrapFile("{$namespace}\\Providers\\MetaTagsServiceProvider"); <-- Error here
 }

**Comment by bplace** [comment]
Getting the same issue indeed, changed the line to 

```
 ServiceProvider::addProviderToBootstrapFile("{$namespace}\\Providers\\MetaTagsServiceProvider");
 return;
```

**Comment by antonioribeiro** [comment]
+1 here

**Comment by butschster** [comment]
Hi @bplace,
Could you please create a PR?

**Comment by bplace** [comment]
Thank you butschster, I was off for the weekend :]
