### ISSUE TITLE
Laravel 10 : Installing/updating any version from 3.0.1 throws a fatal error

### ISSUE THREAD

**Issue by bernig** [butschster/LaravelMetaTags#65]
When installing/updating the package in a Laravel **10** project, a fatal error occurs:

`PHP Fatal error:  A void function must not return a value in /var/www/laravel10/vendor/butschster/meta-tags/src/Console/InstallCommand.php on line 38`

**To Reproduce**
1. Install the latest Laravel 10 version
2. composer require butschster/meta-tags
3. Error

This commit is the cause of the issue: https://github.com/butschster/LaravelMetaTags/commit/43086d3868fcee98deccdb738125322c695f0a65

Note: Forcing the version to 3.0.0 fixes the issue.

**Comment by butschster** [comment]
Fixed! Thx for a bug report!
